AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  extractdata:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 65
      Role: 'arn:aws:iam::779736443620:role/service-role/extract_data_role'
      Layers:
        - 'arn:aws:lambda:us-east-1:779736443620:layer:spotipy_layer:1'
      RuntimeManagementConfig:
        UpdateRuntimeOn: Auto
